server:
  port: 8001
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/springfirstapp
    username: postgres
    password: db
    pool-size: 30
  mongodb:
    host: localhost
    port: 27017
    database: springfirstapp
    uri: mongodb://localhost:27017
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: frontview

axon:
  # serializer:
  #   general: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: account-command-producer
    default-topic: account_topic
    fetcher:
      poll-timeout: 3000
    producer:
      retries: 5
      event-processor-mode: subscribing
    consumer:
      group-id: "account-command-group"
      enable-auto-commit: true
      auto-commit-interval: 3000
    properties:
      security.protocol: PLAINTEXT
